# Generated by Django 5.1.3 on 2024-12-03 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0002_labourpersonalinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='terms_and_condition',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='labourpersonalinformation',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10),
        ),
    ]
