# Generated by Django 5.1.3 on 2024-12-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0003_labour_terms_and_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourpersonalinformation',
            name='profile',
            field=models.ImageField(default='default-images/labour-default-profile.png', upload_to='Labour_profiles/'),
        ),
    ]
