# Generated by Django 5.1.3 on 2025-02-16 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0006_labourworker_dailyattendance_monthlysalary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labourworker',
            name='calculated_salary',
        ),
    ]
