# Generated by Django 5.1.3 on 2025-02-16 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0007_remove_labourworker_calculated_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlysalary',
            name='calculated_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
