# Generated by Django 5.1.3 on 2024-12-18 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labour', '0005_alter_labourpersonalinformation_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartiesDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=255)),
                ('party_name', models.CharField(max_length=255)),
                ('party_mobile', models.CharField(max_length=15)),
                ('address', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('labour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties_details', to='labour.labour')),
            ],
            options={
                'verbose_name': 'Party Detail',
                'verbose_name_plural': 'Parties Details',
                'ordering': ['party_name'],
            },
        ),
    ]
