# Generated by Django 5.1.3 on 2025-02-12 09:16

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partiesdetail',
            name='ido',
        ),
        migrations.AddField(
            model_name='partiesdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partiesdetail',
            name='llid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='partiesdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
