# Generated by Django 5.1.3 on 2024-12-19 03:59

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partiesdetail',
            name='id',
        ),
        migrations.AddField(
            model_name='partiesdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 19, 3, 59, 33, 515554, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partiesdetail',
            name='llid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='partiesdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
